### ISSUE TITLE
Funky error on remove

### ISSUE THREAD

**Issue by andrerfneves** [jagi/meteor-astronomy#123]
Jagi, 

Congrats on the 1.0. Looks great, especially the documentation! 
I am however running into a funny problem on .remove() of an object.

My collection/model
```javascript 
// Create global Mongo collection.
VendorCategories = new Mongo.Collection('vendorcategories');

// Create global class (model).
VendorCategory = Astro.Class({
    name: 'VendorCategory', // Name model.
    collection: VendorCategories, // Associate collection with the model.
    transform: true, // Auto transform objects fetched from collection.
    fields: { // Fields
        name: 'string',
        author: 'string',
        order: 'string'
    },
    behaviors: ['timestamp'] // Add "timestamp" behavior that adds "createdAt" and "updatedAt" fields.
});

```
My click event -- console.log does print out the correct object
```javascript
'click .remove-vendor-category': function() {
        var vendorCategory = this;
        console.log(vendorCategory);
        Meteor.call('removeVendorCategory', vendorCategory, function(err) {
            if (!err) {
                console.log('deleted');
            } else {
                vendorCategory.catchValidationException(err);
                console.log('error');
                alertify.error('Error');
            }
        });
    }
```
And my method
```javascript
    'removeVendorCategory': function(vendorCategory) {
        vendorCategory.remove(); 
    }
```
Saving or updating the document works but when I try to remove any object I receive this error:

```bash
I20151007-12:00:53.964(-4)? Exception while invoking method 'removeVendorCategory' { stack: 'TypeError: Object [object Object] has no method \'remove\'\n    at [object Object].Meteor.methods.removeVendorCategory (server/vendors/vendor-methods.js:25:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2554:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1692:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/Users/andreneves1/.meteor/packages/promise/.0.5.0.13bmo4j++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)\n    at doResolve (/Users/andreneves1/.meteor/packages/promise/.0.5.0.13bmo4j++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)',

I20151007-12:00:53.964(-4)?   source: 'method' }
```
Line 25 on vendor-methods.js refers to the removeVendorCategory method above.

I'm out of things to try. Have pretty much rewritten the entire collection/model/methods multiple times and have gotten to the same place. All my astronomy packages are also up to date. What am I doing wrong?

Thanks!

**Comment by jagi** [comment]
Hi thanks! Remove the line `transform: true` and it will work. From 1.0 there is a change in how the transform property works. You can now specify your custom transform function using it. The transform function is always used in 1.0 until you turn it off for an individual query.

**Comment by andrerfneves** [comment]
Thank god! I knew it had to be missing something.
Thanks again!

**Comment by jagi** [comment]
No problem :)
