### ISSUE TITLE
Can't pull from an array nested in an object nested in an object

### ISSUE THREAD

**Issue by ianmartorell** [jagi/meteor-astronomy#152]
I have this class:

```javascript
var Thing = Astro.Class({
	name: 'Thing',
	collection: Things,
	fields: {
		obj: {
			type: 'object',
			default: function() {
				return {};
			}
		}
	}
});
```

Now, if I do this:

```javascript
var thing = new Thing();
thing.set('obj.asd', {});
thing.save()
thing.set('obj.asd.arr', []);
thing.save();
thing.push('obj.asd.arr', 'admin') // this works
thing.save()
thing.pull('obj.asd.arr', 'admin') // this throws the following error:

TypeError: Cannot call method 'plain' of undefined
    at packages/jagi_astronomy/lib/modules/fields/pull.js:94:1
    at packages/underscore/packages/underscore.js:213:1
    at Array.some (packages/es5-shim/packages/es5-shim.js:575:1)
    at _.some._.any (packages/underscore/packages/underscore.js:262:1)
    at Function._.find._.detect (packages/underscore/packages/underscore.js:212:1)
    at packages/jagi_astronomy/lib/modules/fields/pull.js:93:1
    at runCallback (packages/jagi_astronomy/lib/modules/fields/utils.js:16:1)
    at next (packages/jagi_astronomy/lib/modules/fields/utils.js:46:1)
    at next (packages/jagi_astronomy/lib/modules/fields/utils.js:63:1)
    at next (packages/jagi_astronomy/lib/modules/fields/utils.js:63:1)
```
However, `thing.obj.asd.arr` is definitely not undefined:

```javascript
console.log(thing.get('obj.asd.arr'))

[ 'admin' ]
```

**Comment by jagi** [comment]
In deed there was a bug. I've fixed it in the 1.1.5 version. I hope it's the last one bug in the `pull` method. I haven't made detailed tests for this method and that's why there were many bug there.

**Comment by ianmartorell** [comment]
Thanks! It works now!

**Comment by jagi** [comment]
Good :)
