### ISSUE TITLE
Not a function Error

### ISSUE THREAD

**Issue by colinshen** [jagi/meteor-astronomy#194]
my codes
```
Funds = new Mongo.Collection("funds");
Fund = Astro.Class({
    name: 'Fund',
    collection: Funds,
    fields:{
        fund_name: {
            type: 'string',
            validator:[
                Validators.required(),
                Validators.string(),
                Validators.unique()
            ]
        },
    },
    behaviors: {
        timestamp: {
            hasCreatedField: true,
            createdFieldName: 'createdAt',
            hasUpdatedField: true,
            updatedFieldName: 'updatedAt'
        }
    }
});
Meteor.methods({
    '/fund/create': function(data){
        var fund = new Fund();
        fund.set({
            fund_name:"test1"
        });
        if (fund.validate()) {
            fund.save();
            return fund;
        }
        fund.throwValidationException();
    }
});
```
In console I got this
```
Exception while simulating the effect of invoking '/fund/create' TypeError: Fund is not a function(…) TypeError: Fund is not a function
    at fundCreate (http://localhost:3000/app/model/funds.js?fc80801769917dd29894e7b6f218d104c8cc3427:57:20)
    at http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3911:25
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:971:17)
    at _.extend.apply (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3902:54)
    at _.extend.call (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3780:17)
    at call (http://localhost:3000/packages/angular-meteor-data.js?3aefb331daf81ba7d80cf798e204efe5242a9bce:1350:19)
    at CreateFundCtrl.vm.createFund (http://localhost:3000/app/client/funds/createFund/controllers/CreateFund.js?b8bed4bb7388c4bc4694dc72ff1a0f6968df68b9:9:17)
    at fn (eval at <anonymous> (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:13345:15), <anonymous>:4:260)
    at callback (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:23572:17)
    at Scope.$eval (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16012:28)
```

**Comment by colinshen** [comment]
I do not know, I use the same code to create another collection. It worked perfectly. Only when the name is Fund...

**Comment by jagi** [comment]
Are you sure that the Fund class is defined in both environments? client and server

**Comment by colinshen** [comment]
I created a model folder in root folder, so it should work both client and server

**Comment by jagi** [comment]
Ok so the files load order can matter. Try printing `console.log(1)`, `console.log(2)` at the beginning of two files. Print `1` in the file where the `Fund` class is defined and `2` where the method is defined. If you get the correct order `1, 2` that means that problem is somewhere else. But if you get `2, 1` it means that you have to manipulate files order.

**Comment by pysingh09** [comment]
I'm getting the same error. I'm running the below code in a single file.

```js
import {
    Class
} from 'meteor/jagi:astronomy'
const Posts = new Mongo.Collection('posts');
if (!Posts.find({}).fetch().length) {
    Posts.insert({
        'name': "Test"
    });
    Posts.remove({});
}

const Post = Class.create({ // Getting error In this Line.
    name: 'Post',
    collection: Posts,
    fields: {
        title: {
            type: String,
            validators: [{
                type: 'minLength',
                param: 3
            }]
        },
        userId: String,
        publishedAt: Date
    },
    behaviors: {
        timestamp: {}
    }
});
```

Getting the below error.

TypeError: Class.create is not a function
    at meteorInstall.colllections.collections.js (colllections/collections.js:23:20)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /home/psingh/hom/hom-backend/.meteor/local/build/programs/server/app/app.js:3291:1
    at /home/psingh/hom/hom-backend/.meteor/local/build/programs/server/boot.js:338:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/psingh/.meteor/packages/meteor-tool/.1.5.1.puot9a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/psingh/hom/hom-backend/.meteor/local/build/programs/server/boot.js:158:5
    at /home/psingh/hom/hom-backend/.meteor/local/build/programs/server/boot.js:387:5
    at Function.run (/home/psingh/hom/hom-backend/.meteor/local/build/programs/server/profile.js:510:12)

what can be the issue here?

**Comment by lukejagodzinski** [comment]
@pysingh Is this an entire code in the file? The error says that the bug is in the `collections.js` file in the line number 23. Is the line `const Post = Class.create({` the line number 23? Are you sure that error comes from this file?

PS. Please, format your code properly when posting an issue on GH. I've already fixed it but wrong formatting makes it really hard to read a code.

**Comment by pysingh09** [comment]
@jagi Yes, the entire code is in a single file. [here](https://github.com/jagi/meteor-astronomy/files/1361727/collections.txt) it is. (please rename the file to collections.js)

Please let me know if you need anything else.

Thanks

**Comment by lukejagodzinski** [comment]
You have a bug in your code. You're redeclaring the `Class` variable:

- `Class = new Mongo.Collection('class');`
- `import { Class } from 'meteor/jagi:astronomy';`

Remove the first line
