### ISSUE TITLE
Custom Type 'plain' function not called

### ISSUE THREAD

**Issue by jaskinn** [jagi/meteor-astronomy#207]
I'm attempting to create a custom type (for a 'moment' object), however when I go to save a document it seems to be crashing in 'Class.events.toJSONValue'. My assumption is that my 'plain' function is incorrect, but it doesn't seem to being called.

```
meteor://💻app/packages/momentjs_moment/packages/momentjs_moment.js:186:1: TypeError: Object [object Object] has no method 'getTime'
  at new Moment (meteor://💻app/packages/momentjs_moment/packages/momentjs_moment.js:186:1)
  at Moment.clone (meteor://💻app/packages/momentjs_moment/packages/momentjs_moment.js:1848:1)
  at Moment.moment_format__toISOString (meteor://💻app/packages/momentjs_moment/packages/momentjs_moment.js:1944:1)
  at Object.stringify (native)
  at Object.stringify (/Users/.meteor/packages/ecmascript-runtime/.0.2.6.1ld1cio++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.symbol.js:127:21)
  at Object.EJSON.stringify (meteor://💻app/packages/ejson/ejson.js:343:1)
  at Class.events.toJSONValue (meteor://💻app/packages/jagi_astronomy/lib/modules/fields/ejson.js:14:1)
  at meteor://💻app/packages/jagi_astronomy/lib/modules/core/events.js:52:1
  at Array.every (meteor://💻app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:507:1)
  at Function._.every._.all (meteor://💻app/packages/underscore/underscore.js:219:1)
  at Object._.extend.emit (meteor://💻app/packages/jagi_astronomy/lib/modules/core/events.js:50:1)
  at Class.methods.toJSONValue (meteor://💻app/packages/jagi_astronomy/lib/modules/ejson/init_module.js:18:1)
  at meteor://💻app/packages/ejson/ejson.js:168:1
  at Object.Meteor._noYieldsAllowed (meteor://💻app/packages/meteor/fiber_helpers.js:11:1)
  at Object.builtinConverters.toJSONValue (meteor://💻app/packages/ejson/ejson.js:167:1)
  at toJSONValueHelper (meteor://💻app/packages/ejson/ejson.js:237:1)
  at Object.EJSON.toJSONValue (meteor://💻app/packages/ejson/ejson.js:249:1)
  at Object.EJSON.clone (meteor://💻app/packages/ejson/ejson.js:496:1)
  at meteor://💻app/packages/jagi_astronomy/lib/modules/storage/init_definition.js:119:1
  at Array.forEach (meteor://💻app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
  at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:105:1)
  at Class.prototypeMethods.save (meteor://💻app/packages/jagi_astronomy/lib/modules/storage/init_definition.js:118:1)
  at meteor://💻app/tests/jasmine/server/integration/shifts.js:61:15
```

```
Astro.createType({
    name: 'moment',
    constructor: function MomentType() {
        Astro.BaseField.apply(this, arguments);
    },
    needsCast: function(value) {
        return !moment.isMoment(value);
    },
    cast: function(value) {
        return moment(value);
    },
    needsPlain: function() {
        return true;
    },
    plain: function(value) {
        return value.toDate();
    }
});
```

This type is being used as in a nested class:
```
TimePeriod = Astro.Class({
    name: "TimePeriod",
    fields: {
        start: {
            type: "moment",
            immutable: true,
            validator: Validators.moment()
        },
        finish: {
            type: "moment",
            immutable: true,
            optional: true,
            validator: Validators.and([
                Validators.moment(),
                Validators.laterThan("start")
            ])
        }
    }
});
```

**Comment by jagi** [comment]
Change the `needsPlain` method to:

```js
needsPlain: function() {
  return moment.isMoment(value);
}
```

and it should work. Let me know.

**Comment by jaskinn** [comment]
I made that change, but unfortunately it didn't make any difference. I added some 'console.log' into each function and the only two that seem to be called are the 'constructor' and 'needsCast'.

**Comment by jagi** [comment]
So, you have to create reproduction repository because problem can be somewhere else
