### ISSUE TITLE
Meteor 1.3, "collection" property has to be an instance of the "Mongo.Collection" 

### ISSUE THREAD

**Issue by Hamatek** [jagi/meteor-astronomy#268]
Hello,

Im trying astronomy with meteor 1.3, I set my class as usual I have got something like this:

```javascript
import {Mongo} from 'meteor/mongo';
Games = new Mongo.Collection('games');

export const Game = Astro.Class({
    name: 'Game',
    collection: 'Games',
    fields: {
        createdAt: 'date',
        endAt: 'date'
});
```
I can see that my Games collection is created, but get this error on rebuild:

```javascript
Error: The "collection" property has to be an instance of the "Mongo.Collection" in the "Game" class

at Function.checkSchemaDefinition (packages/jagi_astronomy/lib/modules/storage/init_definition.js:227:1)
at Function.onInitDefinitionStorage (packages/jagi_astronomy/lib/modules/storage/init_definition.js:248:1)
at packages/jagi_astronomy/lib/modules/core/classes.js:27:1
at packages/jagi_astronomy/lib/modules/core/events.js:68:1
at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:419:1)
at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
at Object._.extend.each (packages/jagi_astronomy/lib/modules/core/events.js:64:1)
at Function.methods.extend (packages/jagi_astronomy/lib/modules/core/classes.js:26:1)
at Object.Astro.createClass.Astro.Class (packages/jagi_astronomy/lib/modules/core/classes.js:80:1)
at meteorInstall.lib.models.game.jsx (lib/models/game.jsx:33:27)

```

**Comment by Andrew1431** [comment]
collection: Games, not collection: 'Games'. You're just passing it a string. :palm_tree:

**Comment by jagi** [comment]
@Hamatek exactly what @Andrew1431 said. You are passing string `"Games"` instead of collection `Games`

**Comment by Hamatek** [comment]
@Andrew1431 & @jagi  thanks for pointing this out lol... sorry I assumed too quickly that it was linked to meteor 1.3 and I didn't read my code properly ..., 
Everything works fine now thanks for your quick answers ! :)
