### ISSUE TITLE
Upgrade to Meteor 1.3

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#316]
After upgrading to the latest version of Astronomy `rc7` and to Meteor 1.3 final. I am getting this:

```bash
/Users/talhaasad/.meteor/packages/meteor-tool/.1.3.0_3.197bwrg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
(STDERR)             throw(ex);
(STDERR)                   ^
(STDERR) ReferenceError: fieldDefinition is not defined
(STDERR)     at checkTypeExistence (packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:15:18)
(STDERR)     at packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:48:7
(STDERR)     at /Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4143:15
(STDERR)     at baseForOwn (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:2669:24)
(STDERR)     at /Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4112:18
(STDERR)     at Function.forEach (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7828:11)
(STDERR)     at Module.onApplyDefinition (packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:23:5)
(STDERR)     at packages/jagi:astronomy/lib/core/class.js:174:11
(STDERR)     at packages/jagi:astronomy/lib/core/module.js:95:4
(STDERR)     at arrayEach (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:483:11)
(STDERR)     at Function.forEach (/Users/talhaasad/.meteor/packages/stevezhu_lodash/.4.6.1.2yf9lf++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7827:11)
(STDERR)     at Function.forEach (packages/jagi:astronomy/lib/core/module.js:94:5)
(STDERR)     at Function.extend (packages/jagi:astronomy/lib/core/class.js:161:10)
(STDERR)     at Function.create (packages/jagi:astronomy/lib/core/class.js:103:9)
(STDERR)     at meteorInstall.collections.activities.js (collections/activities.js:3:30)
(STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
```

Any ideas what could be causing this, i have a feeling its something very basic.

**Comment by talha-asad** [comment]
Seems to me the culprit is https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/fields/hooks/apply_definition.js#L15

**Comment by talha-asad** [comment]
I had a stupid typo in my schema which was being ignored previously haha. However i also found a typo in your code @jagi. I think you ought to fix it for next release.

**Comment by jagi** [comment]
Oh thanks for noticing it. I will make an update.

**Comment by peXed** [comment]
I have the same issue. Will the fix be in rc8 and when will you release rc8? :)

**Comment by jagi** [comment]
I'm just working on rc8. Should be soon. I think it will be one of the last rc version before 2.0 release

**Comment by peXed** [comment]
Thanks for the fast reply! Looking forward to it! :+1:
