### ISSUE TITLE
undefined args.doc.type in resolveParam(args) of validators

### ISSUE THREAD

**Issue by laurentpayot** [jagi/meteor-astronomy#413]
After commit 469cf99db04b792b534dd26f8ade4f509edad4dc `args.doc.type` in `resolveParam(args)` for `maxLength` validator (and maybe other validators) is **undefined**.

_(in coffeescript)_

``` coffeescript
ItemsCol = new Mongo.Collection('items')
Item = Astro.Class.create(
    name: 'Item'
    collection: ItemsCol
    secured: true
    # default (untranslated) error messages on server
    resolveError: ((args) -> translateErrorMessage(args)) if Meteor.isClient
    typeField: 'type'
    fields:
        choices:
            type: [Choice]
            default: -> [new Choice, new Choice, new Choice]
            validators: [
                {type: 'minLength', param: 3}
                {type: 'maxLength', resolveParam: (args) -> if args.doc.type is 'Foo' then MAX_CHOICES_NB else 3}
            ]
)

Foo = Prem.inherit(
    name: 'Foo'
)
```

So when creating a new Foo I get:

```
W20160605-20:25:42.386(2)? (STDERR) /home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160605-20:25:42.386(2)? (STDERR)                             throw(ex);
W20160605-20:25:42.386(2)? (STDERR)                                   ^
W20160605-20:25:42.564(2)? (STDERR) Error: Length of "choices" has to be at most 3 [validation-error]
W20160605-20:25:42.564(2)? (STDERR)     at new _class (packages/mdg:validation-error/validation-error.js:14:12)
W20160605-20:25:42.565(2)? (STDERR)     at throwError (packages/jagi:astronomy/lib/modules/validators/validator.js:63:15)
W20160605-20:25:42.565(2)? (STDERR)     at Validator.validate (packages/jagi:astronomy/lib/modules/validators/validator.js:89:9)
W20160605-20:25:42.565(2)? (STDERR)     at _validators2.default.(anonymous function) (packages/jagi:astronomy/lib/modules/validators/validator.js:101:17)
W20160605-20:25:42.565(2)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:125:13
W20160605-20:25:42.565(2)? (STDERR)     at arrayEach (/home/laurent/meteor/myapp/meteor/.meteor/local/isopacks/jagi_astronomy/npm/node_modules/lodash/lodash.js:498:11)
W20160605-20:25:42.565(2)? (STDERR)     at Function.forEach (/home/laurent/meteor/myapp/meteor/.meteor/local/isopacks/jagi_astronomy/npm/node_modules/lodash/lodash.js:8382:11)
W20160605-20:25:42.565(2)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:119:9
W20160605-20:25:42.565(2)? (STDERR)     at catchValidationError (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:40:7)
W20160605-20:25:42.565(2)? (STDERR)     at packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:69:28
```

**Comment by lukejagodzinski** [comment]
I don't think that it may have anything to do with this commit. Can you create reproduction?

**Comment by laurentpayot** [comment]
Well I'm using inheritance and `type` field disappeared from my objects after that commit. After going back to previous commit with `git reset --hard 50424909148f65e7992607b25e36677f0fa1469b` everything is fine.
Still want me to create reproduction ?

**Comment by lukejagodzinski** [comment]
Oh I see. It will be back in the next commit. I was just playing with different type of inheritance however it doesn't work well. I have a different solution which requires the type field to be in a doc.
