### ISSUE TITLE
Exception while invoking method '/Astronomy/insert' TypeError: undefined is not a function

### ISSUE THREAD

**Issue by qunabu** [jagi/meteor-astronomy#449]
I cannot find any related issues on this so I'm posting this here 

I've created a collection with 

``` javascript
import { Mongo } from 'meteor/mongo';
import { Class } from 'meteor/jagi:astronomy';

export const Blocks = new Mongo.Collection('blocks');
export const Block = Class.create({
  name: 'Block',
  collection: Blocks,
  behaviors: {
    timestamp: {}
  },
  secured: {
    insert: false,
    update: false
  }
});
```

then trying to save something with 

``` javascript

import { Blocks } from '../../api/blocks.js';
import { Block } from '../../api/blocks.js';

let block = new Block();
block.block_id = "about";
block.content = 'Lorem ipsum';
try {
  block.save();
} catch(er) {
  console.error(er);
}
```

I get and error `Exception while invoking method '/Astronomy/insert' TypeError: undefined is not a function`

whole error stack is 

```
I20160720-15:06:09.601(2)? Exception while invoking method '/Astronomy/insert' TypeError: undefined is not a function
I20160720-15:06:09.693(2)?     at classInsert (packages/jagi:astronomy/lib/modules/storage/utils/class_insert.js:22:15)
I20160720-15:06:09.693(2)?     at [object Object].insert (packages/jagi:astronomy/lib/modules/storage/meteor_methods/insert.js:4:10)
I20160720-15:06:09.694(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160720-15:06:09.694(2)?     at packages/ddp-server/livedata_server.js:711:19
I20160720-15:06:09.694(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160720-15:06:09.694(2)?     at packages/ddp-server/livedata_server.js:709:40
I20160720-15:06:09.694(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160720-15:06:09.695(2)?     at packages/ddp-server/livedata_server.js:707:46
```

similar code works for other collections.

**Comment by lukejagodzinski** [comment]
Where are you executing this code? In a meteor method? The problem is that Astronomy can't find a class. You may be missing some import. Try creating reproduction - that way you can find a problem in your code.

**Comment by qunabu** [comment]
I'll try to explain this 
In `client/main.js` I have `import '/imports/startup/client';`
where I have iron router setup 

``` javascript
import '../../ui/pages/blocks';
Router.map(function () {
//....
this.route('blocks');
//....
});
```

in `ui/pages/blocks` i have 

``` javascript
import './blocks.html';

import { Block } from '../../api/blocks.js';

Template.Blocks.events({
  'submit .about-text'(event) {
    event.preventDefault();

    let block = new Block();
    block.block_id = "about";
    block.content = 'Lorem ipsum';
    block.save();

  },
});
```

and `blocks.html` is just 

``` html
<template name="Blocks">
  <form class="about-text">
    <textarea class="wysiwyg" name="about_block" id="about_block"></textarea>
    <button>Save</button>
  </form>
</template>
```

`api/blocks.js` 

``` javascript
import { Mongo } from 'meteor/mongo';
import { Class } from 'meteor/jagi:astronomy';

export const Blocks = new Mongo.Collection('blocks');
export const Block = Class.create({
  name: 'Block',
  collection: Blocks,
  behaviors: {
    timestamp: {}
  },
  secured: {
    insert: false,
    update: false
  }
});
```

clicking on `<button>Save</button>` reproduces that error. 

I've made a test in client.js and pasting just this code throws me same error 

``` javascript
import { Mongo } from 'meteor/mongo';
import { Class } from 'meteor/jagi:astronomy';

export const Blocks = new Mongo.Collection('blocks');
export const Block = Class.create({
  name: 'Block',
  collection: Blocks,
  behaviors: {
    timestamp: {}
  },
  secured: {
    insert: false,
    update: false
  }
});

let block = new Block();
block.content = 'Lorem Ipsum'
block.save();

```

**Comment by qunabu** [comment]
Seems like import was missing for that api in `server/main.js`
