### ISSUE TITLE
Is the `validateAll` and `validate` functions meant to run only on the server?

### ISSUE THREAD

**Issue by THPubs** [jagi/meteor-astronomy#461]
Hi, I was trying to validate the data the client entered before calling a meter method and saving them. The problem is, when I run either `validateAll` or `validate` from the client,  I get the following error :

```
I20160727-12:05:36.488(5.5)? Exception while invoking method '/Astronomy/validate' Error: Did not check() all arguments during call to '/Astronomy/validate'
I20160727-12:05:36.489(5.5)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:462:1)
I20160727-12:05:36.489(5.5)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:110:1)
I20160727-12:05:36.489(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1701:18)
I20160727-12:05:36.489(5.5)?     at packages/ddp-server/livedata_server.js:711:19
I20160727-12:05:36.489(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160727-12:05:36.489(5.5)?     at packages/ddp-server/livedata_server.js:709:40
I20160727-12:05:36.489(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160727-12:05:36.490(5.5)?     at packages/ddp-server/livedata_server.js:707:46
I20160727-12:05:36.490(5.5)?     at tryCallTwo (/home/pubudu/.meteor/packages/promise/.0.7.3.1nn5d59++os+web.browser+web.cordova/npm/node_modules/promise/lib/core.js:45:5)
I20160727-12:05:36.490(5.5)?     at doResolve (/home/pubudu/.meteor/packages/promise/.0.7.3.1nn5d59++os+web.browser+web.cordova/npm/node_modules/promise/lib/core.js:200:13)
```

Im using the `audit-argument-checks` package. What is the normal flow to get the validation errors before saving the document?

**Comment by lukejagodzinski** [comment]
You are missing some imports

**Comment by THPubs** [comment]
@jagi Thanks but I can't understand what I'm missing. Here's my action :

```
export default {
  signup({Meteor, LocalState, FlowRouter, Collections}, organization, user) {
    document.getElementById('loading').style.display = 'flex';

    const newOrganization = new Collections.Organizations();

    newOrganization.set(organization);
    newOrganization.validateAll((errors) => {
      console.log(errors);
    });
  }
};
```

If there are validation errors, it return the error without any issue. But if there are no errors, it throws the error I mentioned above.

**Comment by lukejagodzinski** [comment]
It's not about your action but about `import`. You didn't import class/Astronomy in some place. It happened to me only once and it was long time ago but it was lack of import. It also happened several times to Astronomy users and all they had to do is to check if they have imports in all places class is used. You're probably calling some method on client and server and you forgot to import class somewhere.
