### ISSUE TITLE
Please help with error...

### ISSUE THREAD

**Issue by joetidee** [jagi/meteor-astronomy#508]
I am getting the following error, but I cannot seem to trace it back to anything obvious - are you able to point me i the right direction?

```
Exception while invoking method '/save' TypeError: Cannot read property 'some_id' of undefined
I20161004-22:17:23.343(0)?     at packages/jagi_astronomy/lib/modules/fields/modifiers.js:255:1
I20161004-22:17:23.343(0)?     at runCallback (packages/jagi_astronomy/lib/modules/fields/utils.js:16:1)
I20161004-22:17:23.344(0)?     at Object.Astro.utils.fields.traverseNestedDocs (packages/jagi_astronomy/lib/modules/fields/utils.js:22:1)
I20161004-22:17:23.344(0)?     at packages/jagi_astronomy/lib/modules/fields/modifiers.js:250:1
I20161004-22:17:23.344(0)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20161004-22:17:23.345(0)?     at Class.proto._getModifier (packages/jagi_astronomy/lib/modules/fields/modifiers.js:247:1)
I20161004-22:17:23.345(0)?     at packages/jagi_astronomy/lib/modules/fields/modifiers.js:294:1
I20161004-22:17:23.345(0)?     at Array.forEach (native)
I20161004-22:17:23.346(0)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20161004-22:17:23.346(0)?     at Class.proto._getModifiers (packages/jagi_astronomy/lib/modules/fields/modifiers.js:293:1)
```

**Comment by lukejagodzinski** [comment]
There is no such Meteor method like `/save` in Astronomy so it's probably your custom method where is a problem. You have to provide some code.

**Comment by joetidee** [comment]
Yes, the save method is my own, but in the method, the only place that some_id is defined is in the Astronomy validate() method - so would you be able to tell me what I should be looking for to be able to debug this?

**Comment by lukejagodzinski** [comment]
Oh you're probably using Astronomy v1. I'm not supporting v1 beside critical bugs. As I said without code it's almost impossible to help.
