### ISSUE TITLE
TypeError: Cannot read property 'nextObject' of undefined

### ISSUE THREAD

**Issue by dnish** [jagi/meteor-astronomy#662]
Hey,
when I try to remove a doc via <code>video.remove()</code> (on server side) I get the following error:

```

I20180311-00:31:34.052(1)? Exception while invoking method 'videos.remove' TypeError: Cannot read property 'nextObject' of undefined
I20180311-00:31:34.052(1)?     at new SynchronousCursor (packages/mongo/mongo_driver.js:1007:14)
I20180311-00:31:34.052(1)?     at MongoConnection._createSynchronousCursor (packages/mongo/mongo_driver.js:984:10)
I20180311-00:31:34.052(1)?     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:866:45)
I20180311-00:31:34.052(1)?     at classRemove (packages/jagi:astronomy/lib/modules/storage/utils/class_remove.js:33:8)
I20180311-00:31:34.052(1)?     at Function.remove (packages/jagi:astronomy/lib/modules/storage/class_static_methods/remove.js:49:18)
I20180311-00:31:34.052(1)?     at DDPCommon.MethodInvocation.videos.remove (imports/server/methods/videos.js:34:19)
I20180311-00:31:34.052(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180311-00:31:34.053(1)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180311-00:31:34.053(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180311-00:31:34.053(1)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
```

The document stays on the server and wasn't removed.

**Comment by lukejagodzinski** [comment]
It's probably related to your code and note Astronomy. Try preparing reproduction repository.

**Comment by dnish** [comment]
@lukejagodzinski I will check that. If I execute the .remove() within the collections file, everything is working fine, but within my method, it still throws the error above.

**Comment by dnish** [comment]
Can be closed, it was a typ error. I wrote
<code>const video = Video.findOne(id);
Video.remove()</code>

So I called the collection remove and not the one of the object.
