### ISSUE TITLE
Weird error can't trace

### ISSUE THREAD

**Issue by andrerfneves** [jagi/meteor-astronomy#85]
So I randomly started receiving this error regarding my OpenQuestions Astron Model/Collection. I've tried tracing it manually, and with Kadira but I can't seem to find out what exactly is happening. This is causing my CPU usage to go sky high. Any help would be appreciated. Thanks!
```
I20150901-13:56:37.313(-4)? Exception from sub openquestions id WfwX3hhAAJZjvXPxm TypeError: Object function Class() {                                                    // 38
I20150901-13:56:37.313(-4)?     if (!(this instanceof Class)) {                                                 // 39
I20150901-13:56:37.313(-4)?       throw new Error('Use "new" keyword to create an instance');                   // 40
I20150901-13:56:37.314(-4)?     }                                                                               // 41
I20150901-13:56:37.314(-4)?                                                                                     // 42
I20150901-13:56:37.314(-4)?     var self = this;                                                                // 43
I20150901-13:56:37.314(-4)?     var args = arguments;                                                           // 44
I20150901-13:56:37.314(-4)?                                                                                     // 45
I20150901-13:56:37.314(-4)?     // Call default constructor.                                                    // 46
I20150901-13:56:37.314(-4)?     defaultConstructor.apply(self, args);                                           // 47
I20150901-13:56:37.314(-4)?                                                                                     // 48
I20150901-13:56:37.314(-4)?     // Call global constructors by triggering the "initinstance" event. These       // 49
I20150901-13:56:37.315(-4)?     // constructors are mainly defined by modules and behaviors.                    // 50
I20150901-13:56:37.315(-4)?     Astro.eventManager.each('initinstance', function(eventHandler) {                // 51
I20150901-13:56:37.315(-4)?       eventHandler.apply(self, args);                                               // 52
I20150901-13:56:37.315(-4)?     });                                                                             // 53
I20150901-13:56:37.315(-4)?                                                                                     // 54
I20150901-13:56:37.315(-4)?     // Call user defined constructor.                                               // 55
I20150901-13:56:37.315(-4)?     self.constructor.getConstructor().apply(self, args);                            // 56
I20150901-13:56:37.315(-4)?   } has no method 'find'
I20150901-13:56:37.316(-4)?     at [object Object]._handler (app/server/pubs.js:6:26)
I20150901-13:56:37.316(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150901-13:56:37.316(-4)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150901-13:56:37.316(-4)?     at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
I20150901-13:56:37.316(-4)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150901-13:56:37.316(-4)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150901-13:56:37.317(-4)?     at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:77:1
I20150901-13:56:37.317(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150901-13:56:37.317(-4)?     at [object Object].sessionProto.protocol_handlers.sub (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:76:1)
I20150901-13:56:37.317(-4)?     at packages/ddp/livedata_server.js:546:1
```

Here's my collection, just in case:
```javascript
// Create global Mongo collection.
OpenQuestions = new Mongo.Collection('openquestions');

// Create global class (model).
OpenQuestions = Astro.Class({
    name: 'OpenQuestion', // Name model.
    collection: OpenQuestions, // Associate collection with the model.
    transform: true, // Auto transform objects fetched from collection.
    fields: {
        picture: 'string',
        text: 'string',
        userAnswer: 'string',
        correctAnswer: 'string'
    },
    behaviors: ['timestamp'] // Add "timestamp" behavior that adds "createdAt" and "updatedAt" fields.
});
```

**Comment by jagi** [comment]
You have an error the class name should be without the "s" `OpenQuestion` instead of `OpenQuestions`

**Comment by andrerfneves** [comment]
That solves it. Cheers @jagi!

**Comment by jagi** [comment]
No problem :)
